Repository NREL/ThermalNetwork, pull requests merged in 2024-12, with the labels that each got.

#55 Run CI in more cases
  .github/workflows/documentation_site.yml
  .github/workflows/format_and_lint.yml
  .github/workflows/install.yml
  .github/workflows/tests.yml
Labels: tests

#52 feat(geometry): Rotate GeoJSON Polygons when a right angle is found
  thermalnetwork/geometry.py
  thermalnetwork/ground_heat_exchanger.py
  thermalnetwork/network.py
  thermalnetwork/projection.py
  thermalnetwork/tests/test_network.py
  thermalnetwork/tests/test_projection.py
Labels: enhancement

#56 Prep for new version v0.3.1
  .pre-commit-config.yaml
  pyproject.toml
  thermalnetwork/network.py
Labels: ignore for release

#57 Minor updates to Readme file
  README.md
Labels: documentation

#58 Automatically set beginning of loop at a GHE
  demos/sdk_output_skeleton_13_buildings/network.geojson
  demos/sdk_output_skeleton_13_buildings/run/baseline_scenario/ghe_dir/sys_params_proportional.json
  demos/sdk_output_skeleton_13_buildings/run/baseline_scenario/ghe_dir/sys_params_upstream.json
  demos/sdk_output_skeleton_1_ghe/network.geojson
  demos/sdk_output_skeleton_1_ghe/run/baseline_scenario/ghe_dir/sys_params_detailed_geo.json
  demos/sdk_output_skeleton_2_ghe_sequential/network.geojson
  demos/sdk_output_skeleton_2_ghe_staggered/network.geojson
  demos/sdk_output_skeleton_2_ghe_staggered/run/baseline_scenario/ghe_dir/sys_params.json
  thermalnetwork/network.py
Labels: enhancement
